// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_7eikmVm9KXse52K-S6f9i53VOkfxFEI',
    appId: '1:563620499827:web:30bc62260f518779e3f506',
    messagingSenderId: '563620499827',
    projectId: 'flutter-login-ui-fe2d6',
    authDomain: 'flutter-login-ui-fe2d6.firebaseapp.com',
    storageBucket: 'flutter-login-ui-fe2d6.appspot.com',
    measurementId: 'G-DNW2T49XX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBROj-c6Zv38DZPGBjvpEUHJ-LI7EEKngI',
    appId: '1:563620499827:android:a8283c08335aaca1e3f506',
    messagingSenderId: '563620499827',
    projectId: 'flutter-login-ui-fe2d6',
    storageBucket: 'flutter-login-ui-fe2d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF8nCy4l2Nz4v-wC5tGkswv0oDdJ6S7_I',
    appId: '1:563620499827:ios:ba59e69caba47f38e3f506',
    messagingSenderId: '563620499827',
    projectId: 'flutter-login-ui-fe2d6',
    storageBucket: 'flutter-login-ui-fe2d6.appspot.com',
    iosClientId: '563620499827-jj15umjbv3pg1kgpe1o6ceq96doj50sh.apps.googleusercontent.com',
    iosBundleId: 'net.fluttertutorial.flutterLoginUi',
  );
}
